config/routes.rb
Rails.application.routes.draw do

  resources :mutants
  root 'welcome#index'

  resources :teams do
    resources :mutants, only: [] do
      member do
        post :add
      end
    end
  end

end

app/models/mutant.rb
class Mutant < ActiveRecord::Base
  belongs_to :team
  validates :name, presence: true,
                   length: { minimum: 3 }

  validates :superpower, presence: true,
                         length: { minimum: 3 }

  validates :cv, presence: true,
                 length: { minimum: 3 }

  scope :unassigned, -> { where(team_id: nil) }

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :mutants
  validates :name, presence: true,
                   length: { minimum: 3 }
  validates :task, presence: true,
                   length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mutants_controller.rb
class MutantsController < ApplicationController

  def new
    # we added @mutant = Mutant.new in the MutantController is that otherwise @mutant would be nil in our view,
    # and calling @mutant.errors.any? (mutants/new.html.erb) would throw an error.
    @mutant = Mutant.new
  end

  def create
    # render plain: params[:mutant].inspect
    @mutant = Mutant.new(mutant_params)

    if @mutant.save
      redirect_to @mutant
    else
      # The render method is used so that the @mutant object is passed back to the new template when it is rendered.
      # This rendering is done within the same request as the form submission,
      # whereas the redirect_to will tell the browser to issue another request.
      render 'new'
    end
  end

  def show
    @mutant = Mutant.find(params[:id])
  end

  def index
    @mutants = Mutant.all
  end

  def edit
    @mutant = Mutant.find(params[:id])
  end

  def update
    @mutant = Mutant.find(params[:id])

    if @mutant.update(mutant_params)
      redirect_to @mutant
    else
      render 'edit'
    end
  end

  def destroy
    @mutant = Mutant.find(params[:id])
    @mutant.destroy

    redirect_to mutants_path
  end

  def add
    @mutant = Mutant.find(params[:id])
    @team = Team.find(params[:team_id])

    @team.mutants << @mutant
    redirect_to edit_team_url(@team)

  end

  private
    def mutant_params
      params.require(:mutant).permit(:name, :superpower, :cv)
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def new
    @team = Team.new
  end

  def create
   @team = Team.new(team_params)

   if @team.save
     redirect_to @team
   else
     render 'new'
   end
  end

  def team_params
    params.require(:team).permit(:name, :task)
  end

  def show
    @team = Team.find(params[:id])
  end

  def index
    @teams = Team.all
  end

  def edit
    @team = Team.find(params[:id])
    @unassigned_mutants = Mutant.unassigned
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to @team
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mutants_helper.rb
module MutantsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div  class="container">
    <small>
        MutantBoard by <a href="http://www.github.com/NadjaW">NadjaW</a>
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav>
          <ul class="nav navbar-nav pull-right">
           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" > Mutants <b class="caret"></b></a>
             <ul class="dropdown-menu">
                <li>
                  <%= link_to 'List Mutants', mutants_url %>
                  <%= link_to 'New Mutant', new_mutant_url %>
                </li>
             </ul>
           </li>
          </ul>
          <ul>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" > Teams <b class="caret"></b></a>
                <ul>
                  <li>
                    <%= link_to 'List Teams', teams_url %>
                    <%= link_to 'New Team', new_team_url %>
                  </li>
                </ul>
            </li>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MutantBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
    <%= render 'layouts/header' %>

    <section class="container">
        <%= yield %>

    </section>

    <%= render 'layouts/footer' %>

</body>
</html>

app/views/mutants/_form.html.erb
<%= form_for @mutant do |f| %>
  <% if @mutant.errors.any? %>
  <div id="error_explanation">
    <h2>Errors:</h2>
    <% @mutant.errors.full_messages.each do |msg| %>
      <%= msg %><br/>
    <% end %>
  </div>
  <% end %>

  <br>
  <br>

  <p>
    <div class="field form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name %>
        </div>
    </div>
  </p>


  <p>
    <div class="field form-group">
        <%= f.label :superpower, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
            <%= f.text_field :superpower %>
        </div>
    </div>
  </p>

  <p class="cv">
    <%= f.label :cv %><br>
    <%= f.text_area :cv %>
  </p>

  <p style="margin:20px">
    <%= f.submit class: 'btn btn-success btn-xs' %>
  </p>

<% end %>

app/views/mutants/edit.html.erb
<h1>Edit mutant</h1>

<%= render 'form' %>

<%= link_to 'Back', mutants_path, class: 'btn btn-primary btn-xs' %>

app/views/mutants/index.html.erb
<h1>Listing mutants</h1>

<br>
<p style="margin:20px" >
<%= link_to 'New Mutant', new_mutant_path, class: 'btn btn-default' %>
<%= link_to 'Home', root_path, class: 'btn btn-default' %>
</p>
<br>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Superpower</th>
    <th>cv</th>
    <th colspan="4" ></th>
  </tr>

  <% @mutants.each do |mutant| %>
    <tr>
      <td><%= mutant.name %></td>
      <td><%= mutant.superpower %></td>
      <td><%= mutant.cv %></td>
      <td><%= link_to 'Show', mutant_path(mutant), class: 'btn btn-success btn-xs' %></td>
      <td><%= link_to 'Edit', edit_mutant_path(mutant), class: 'btn btn-warning btn-xs' %></td>
      <td><%= link_to 'Delete', mutant_path(mutant), class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/mutants/new.html.erb
<h1>New Mutant Pupil</h1>

<%= form_for :mutant, url: mutants_path do |f| %>

  <% # check if there are any errors with @mutant.errors.any?, 
     # and in that case we show a list of all errors with @mutant.errors.full_messages %>
  <% if @mutant.errors.any? %>
    <div id="error_explanation">
      <% # pluralize is a rails helper that takes a number and a string as its arguments.
         # If the number is greater than one, the string will be automatically pluralized. %>
      <h2><%= pluralize(@mutant.errors.count, "error") %> prohibited this mutant from being saved:</h2>
      <ul>
        <% @mutant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :superpower %><br>
    <%= f.text_field :superpower %>
  </p>

  <p>
    <%= f.label :cv %><br>
    <%= f.text_area :cv %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', mutants_path %>

app/views/mutants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @mutant.name %>
</p>

<p>
  <strong>Superpower:</strong>
  <%= @mutant.superpower %>
</p>

<p>
  <strong>CV:</strong>
  <%= @mutant.cv %>
</p>

<%= link_to 'Back', mutants_path %>

app/views/welcome/index.html.erb
<h1>MutantsBoard</h1>
<h2>Welcome Prof. Xavier</h2>
<p>I wish you a good morning and hope you are superpowerly up today :)</p>
<%= link_to 'List Teams', teams_url, class: 'btn btn-default' %>
<%= link_to 'List Mutants', mutants_url, class: 'btn btn-default' %>